### PR TITLE
…

### PR DESCRIPTION
**Pull request by vestrada**
https://github.com/craftercms/craftercms/issues/3166 - [studio-ui] let user know they don't have access to any sites when sites dashboard is empty #3166

### CODE REVIEW

**Review by rart — CHANGES_REQUESTED** [review]
Same as analog PR

**Comment by vestrada** [comment]
Done

**Review by rart — CHANGES_REQUESTED** [review]
Why is the copyright included multiple times on `main.css`?

**Comment by vestrada** [comment]
Seems like all scss files have included the copyright. There are some files that are imported to main files, that is why you are seeing it multiple times. If we want to remove it we should remove the copyright from imported files.

**Comment by vestrada** [comment]
Done

**Review by rart — APPROVED** [review]

**Pull request merged**
