### PR TITLE
[7261] Do not show paste when cut/paste under cut item's children

### PR DESCRIPTION
**Pull request by jvega190**
https://github.com/craftercms/craftercms/issues/7261

### CODE REVIEW

**Review by rart — COMMENTED** [review]
Did you try excluding paste when creating the action list at item menu?

**Review by rart — APPROVED** [review]

**Comment by sumerjabri** [comment]
Should this be "ready for review" instead of draft?

**Comment by jvega190** [comment]
Yeah, I'll move multiple PRs (including this one) to ready for review after dealing with the bigger PRs (the ones with priority)

**Comment by jvega190** [comment]
@sumerjabri done, this is ready for review now

**Pull request merged**
