### PR TITLE
#3395

### PR DESCRIPTION
**Pull request by jvega190**
[studio-ui] Data sources that perform uploads should show progress bars during the upload #3395
https://github.com/craftercms/craftercms/issues/3395
[studio-ui] Upload Image dialog from Page - Article's file field goes to edge of dialog #3442
https://github.com/craftercms/craftercms/issues/3442

### CODE REVIEW

**Review by rart — CHANGES_REQUESTED** [review]
- https://uppy.io/docs/react/
- Remember to remove all those pesky code comments and console logs once you're done
- Use single quotes

**Comment by jvega190** [comment]
@rart the component being used for this upload (FileInput) is not part of the react implementation in https://uppy.io/docs/react/

**Review by rart — APPROVED** [review]

**Comment by sumerjabri** [comment]
@jvega190 please fix the conflict, and provide a link to the ticket behind this PR.

**Comment by jvega190** [comment]
@sumerjabri done!

**Review by rart — APPROVED** [review]

**Pull request merged**
