### PR TITLE
[3806] Complete community PR translations

### PR DESCRIPTION
**Pull request by jvega190**
https://github.com/craftercms/craftercms/issues/3806

### CODE REVIEW

**Review by rart — CHANGES_REQUESTED** [review]
@jvega190 the idea of doing it on 2019 was to do it on top of the new dialogs that were reactified.

The translations updated on develop will get merged automatically on the regular develop=>2019 pulls that I do.

**Comment by jvega190** [comment]
@rart So this PR should be closed, because the new dialogs don't use those texts. For scheduling we only display 'now' or 'later'

**Comment by rart** [comment]
Verify copy is inline with "publish" instead of "go live" and if so, yes. Close.

**Comment by jvega190** [comment]
Everything is with 'publish'. Closing PR

**Pull request closed without merging**
