### PR TITLE
[4.1.x][6550] Editing Date picker fields via XB is broken

### PR DESCRIPTION
**Pull request by jvega190**
https://github.com/craftercms/craftercms/issues/6550

### CODE REVIEW

**Review by rart — CHANGES_REQUESTED** [review]
I need this triple checked please. It looks this was address on https://github.com/craftercms/studio-ui/pull/3534 for https://github.com/craftercms/craftercms/issues/6368 and it has come back. Let's make sure this is final.

**Comment by jvega190** [comment]
Checked, the control was rendering properly in the first render, but if you closed/opened again it would re-position incorrectly. Now, it resets the top position on each render to avoid those miscalculations. Also, I'm avoiding opening the control when it's already open.

**Review by rart — COMMENTED** [review]
Was it tested also in full forms with multiple controls in different positions in relation to the scroll?

**Comment by jvega190** [comment]
Yeah, tested with full forms and positioning several date-pickers in different positions

**Review by rart — APPROVED** [review]

**Pull request merged**
