### PR TITLE
#3526

### PR DESCRIPTION
**Pull request by vestrada**
https://github.com/craftercms/craftercms/issues/3526 - [studio-ui] Double crafterSite cookie appears after creating site #3526

### CODE REVIEW

**Review by rart — APPROVED** [review]
Code looks correct.

**Review by rart — CHANGES_REQUESTED** [review]
@vestrada, did you test this against the bug?
Did you test 127.0.0.1 and localhost?
Did you test that the cookie overrides the cookie set by, say the preview link on the sites listing?

**Comment by vestrada** [comment]
@rart, yes I did.

**Review by rart — APPROVED** [review]
@sumerjabri clear for merge.

**Pull request merged**
