### PR TITLE
[studio-ui] User first name and last name is not displayed in the Account Management screen #3132

### PR DESCRIPTION
**Pull request by jvega190**
https://github.com/craftercms/craftercms/issues/3132

### CODE REVIEW

**Comment by jvega190** [comment]
@rart  What happens is that user data is being set in two scenarios.

1.  No user logged in studio. When there's no user you need to login, and login callback has user data (in this case the prop is user.name, for example)

2.  User already logged in. When user is already logged in into studio the user data comes from model, and is set on a variable from the freemarker template, parsed and it's retrieved as the user data (in this scenario the props have different names, like user.first_name).

**Review by rart — CHANGES_REQUESTED** [review]
Can we change the FreeMarker prop names to match the API prop names? 
If so, please do.
If not, why not?

**Comment by jvega190** [comment]
@rart yes it was possible, PR updated

**Review by rart — APPROVED** [review]

**Review by rart — CHANGES_REQUESTED** [review]
Please camelcase the attributes

**Review by rart — APPROVED** [review]

**Pull request merged**
