### PR TITLE
[3673] Partial language update

### PR DESCRIPTION
**Pull request by vestrada**
https://github.com/craftercms/craftercms/issues/3673 - [studio-ui] Partial language update #3673

### CODE REVIEW

**Review by rart — CHANGES_REQUESTED** [review]
Please add a "Unsaved changes" message similar to global config view.

**Comment by vestrada** [comment]
Done

**Review by rart — CHANGES_REQUESTED** [review]
Request was for an unsaved changes warning, not a try/catch.
Is there anything on that code that can throw?

**Comment by vestrada** [comment]
Done

**Review by rart — APPROVED** [review]

**Comment by sumerjabri** [comment]
@rart is this going to 3.1.4?

**Comment by rart** [comment]
> @rart is this going to 3.1.4?

Yes!

**Pull request merged**
