### PR TITLE
[5754] On content type builder, pasting on the variable name field prepends gibberish

### PR DESCRIPTION
**Pull request by jvega190**
https://github.com/craftercms/craftercms/issues/5754

### CODE REVIEW

**Review by rart — CHANGES_REQUESTED** [review]
Fixes pending

**Comment by jvega190** [comment]
Latest fixes in [0e734d8](https://github.com/craftercms/studio-ui/pull/3154/commits/0e734d8a97f66de66ae53e80bed6425a3adbda04).

**Review by rart — APPROVED** [review]
What was the cause of the prepended gibberish on paste?

**Comment by jvega190** [comment]
The paste event was causing the issue, since the event is triggered before the input value is updated we were cleaning the value from the control (still not sure why exactly the gibberish). But after updating the event to `input` now we clean/update the actual new value directly from the input, and the issue is not happening anymore

**Pull request merged**
