### PR TITLE
[5537] CMIS upload dialog is sending the form data incorrectly

### PR DESCRIPTION
**Pull request by jvega190**
- https://github.com/craftercms/craftercms/issues/5537
- https://github.com/craftercms/craftercms/issues/5464
- https://github.com/craftercms/craftercms/issues/5465

### CODE REVIEW

**Comment by jvega190** [comment]
Ready. Hold in draft for 4.0.1

**Comment by rart** [comment]
@sumerjabri include in 4.0.0?

**Comment by sumerjabri** [comment]
@rart if very low risk, it would be best to include it as it fixes a real issue.

**Comment by rart** [comment]
It looks like moderately low risk but as I understand, the feature is completely unusable with out this work.

**Review by rart — APPROVED** [review]

**Pull request merged**
