### PR TITLE
[studio-ui] Wrong array initialization in forms-engine #3455

### PR DESCRIPTION
**Pull request by jvega190**
https://github.com/craftercms/craftercms/issues/3455

### CODE REVIEW

**Review by rart — CHANGES_REQUESTED** [review]
This was done this way for a reason. What seems to be the problem?

Removing the space may cause issues writing the xml as the first attribute and the tag name would get concatenated. For example: `<form name=“”>` would result in `<formname=“”>`.
There’s also logic below - in line 2815 - that depends on this initialisation.

**Comment by jvega190** [comment]
There's already an space added in line 2868 to avoid the tag name and attribute to be concatenated. The problem is that the array will be like `[" ", attribute1, ...]` and then they'll be added comma separated, causing the xml to be like `<form ,name="">...` (adds a comma that causes the xml to be incorrect). Line 2815 needs to be removed. Please let me know what you think

**Comment by rart** [comment]
Why are they comma separated? Those should be space-separated. There should be a join invocation somewhere and it should be using space as the separator, not comma.

**Comment by jvega190** [comment]
Oh, yeah.. Actually that is the issue, let me see why is that comma being added, I'll be sending the fix

**Comment by jvega190** [comment]
@rart the problem was that in an else there was no `join` being used to add the attributes. PR updated

**Review by rart — APPROVED** [review]
:)

**Pull request merged**
